name: bookmyspa
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.0-290.4.beta

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_sign_in: ^6.2.1
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  permission_handler: ^11.3.1
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.2
  dtd: ^4.0.0
  flutter_lints: ^6.0.0
  google_fonts: ^6.3.3
  json_rpc_2: ^4.0.0
  path: ^1.9.1
  stack_trace: ^1.12.1
  web: ^1.1.1
  # floating_navbar: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - images/
