// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdoTSqRovU6Yt-XN_FzxXvL_YY_xbLOZM',
    appId: '1:28024749368:web:a8a2b5297d8c56e023d5cd',
    messagingSenderId: '28024749368',
    projectId: 'book-my-spa-5012f',
    authDomain: 'book-my-spa-5012f.firebaseapp.com',
    storageBucket: 'book-my-spa-5012f.firebasestorage.app',
    measurementId: 'G-GTB9606E6X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1IcON0oFP0A7oAw8_0f70SuoxgOzA8UU',
    appId: '1:28024749368:android:d87279fb0cfa16b923d5cd',
    messagingSenderId: '28024749368',
    projectId: 'book-my-spa-5012f',
    storageBucket: 'book-my-spa-5012f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAItMJ1tybEEvR37BQUYFN_c2oRcww3Yo',
    appId: '1:28024749368:ios:43071b89e8e3242e23d5cd',
    messagingSenderId: '28024749368',
    projectId: 'book-my-spa-5012f',
    storageBucket: 'book-my-spa-5012f.firebasestorage.app',
    iosBundleId: 'com.example.bookmyspa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAItMJ1tybEEvR37BQUYFN_c2oRcww3Yo',
    appId: '1:28024749368:ios:43071b89e8e3242e23d5cd',
    messagingSenderId: '28024749368',
    projectId: 'book-my-spa-5012f',
    storageBucket: 'book-my-spa-5012f.firebasestorage.app',
    iosBundleId: 'com.example.bookmyspa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdoTSqRovU6Yt-XN_FzxXvL_YY_xbLOZM',
    appId: '1:28024749368:web:c96cea48a4578c6923d5cd',
    messagingSenderId: '28024749368',
    projectId: 'book-my-spa-5012f',
    authDomain: 'book-my-spa-5012f.firebaseapp.com',
    storageBucket: 'book-my-spa-5012f.firebasestorage.app',
    measurementId: 'G-KPHV7KLL4Y',
  );
}
